dependencies:
- name: mariadb
  version: ~7.6.1
  repository: https://charts.bitnami.com/bitnami
  alias: database
  condition: database.enabled
- name: redis
  version: ~10.7.11
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: onlyoffice
  version: ~1.10
  repository: https://arkadym.github.io/helm
  condition: onlyoffice.enabled
- name: elasticsearch
  version: ~1.6
  repository: https://arkadym.github.io/helm
  condition: elasticsearch.enabled
- name: kube-backup
  version: ~1.5
  repository: https://arkadym.github.io/helm
  alias: backup-db
  condition: backup-db.enabled
- name: kube-backup
  version: ~1.5
  repository: https://arkadym.github.io/helm
  alias: backup-config
  condition: backup-config.enabled
- name: kube-backup
  version: ~1.5
  repository: https://arkadym.github.io/helm
  alias: backup-data-sync
  condition: backup-data-sync.enabled
