apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if and .Values.nextcloud.config.admin (not .Values.nextcloud.config.admin.password) }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- end }}
data:
{{- if and .Values.nextcloud.config.admin }}
{{- if .Values.nextcloud.config.admin.password }}
  admin-password: {{ .Values.nextcloud.config.admin.password | b64enc | quote }}
{{- else }}
  admin-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- end }}
  smtp-password: {{ .Values.nextcloud.config.email.password | b64enc | quote }}
